name: WKTECH
favicon: null
layout_spectrum: 0.3466698
typography_spectrum: 0.03763473
title: 'WKTECH '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9685214
  lightness: 0.9017263
  saturation: 0.3625566
  rhythmicContrast: 0.5278212
purpose: []
